{
  "hash": "b441b7b1498ef223ffffe12436706f70",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Who Do We Know the Least About?\"\nsubtitle: \"Measuring uncertainty in American Community Survey data\"\nauthor: \"Tegan Lochner\"\ndate: today\nformat:\n  html:\n    toc: true\n    code-fold: false\nexecute:\n  warning: false\n  message: false\n---\n\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidycensus)\n```\n:::\n\n\n---\n\n## The question\n\nEvery number the American Community Survey publishes is an estimate drawn from a\nsample, not a count. That means every number comes with a margin of error — a\nstatement about how wrong it might be.\n\nMost people ignore it. In this assignment, you won't.\n\nIn this analysis, I will look at median gross rent in Illinois. I will explore which communities are measured the most and least reliably, and what impacts that could have on public policy. \n\n---\n\n## Choosing what to measure\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_state <- \"IL\"        # two-letter abbreviation, in quotes\nmy_variable <- \"B25064_001\"     # the variable code, in quotes\n```\n:::\n\n\n## Pulling the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- get_acs(\n  geography = \"county\",\n  variables = my_variable,\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\"\n)\n```\n:::\n\n\nLet's look at what came back.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 102   5\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  GEOID NAME                       variable   estimate   moe\n  <chr> <chr>                      <chr>         <dbl> <dbl>\n1 17001 Adams County, Illinois     B25064_001      826    43\n2 17003 Alexander County, Illinois B25064_001      540   214\n3 17005 Bond County, Illinois      B25064_001      735    34\n4 17007 Boone County, Illinois     B25064_001     1011    71\n5 17009 Brown County, Illinois     B25064_001      724   119\n6 17011 Bureau County, Illinois    B25064_001      838    66\n```\n\n\n:::\n:::\n\n\n\n**[There are 102 rows of data which correlates to the 102 counties in Illinois. ]**\n\n\n---\n\n## How big is the margin of error?\n\nA margin of error of 3,000 means something very different for an estimate of 20,000\nthan for an estimate of 200,000. To compare across places, we need it as a\npercentage.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data |> \n  mutate(moe_pct = moe / estimate * 100)\n```\n:::\n\n\n\nNow sort to see which counties are measured least reliably.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data |> \n  arrange(desc(moe_pct)) |> \n  select(NAME, estimate, moe, moe_pct) |> \n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   NAME                       estimate   moe moe_pct\n   <chr>                         <dbl> <dbl>   <dbl>\n 1 Hardin County, Illinois         342   156    45.6\n 2 Alexander County, Illinois      540   214    39.6\n 3 Pope County, Illinois           438   134    30.6\n 4 Hamilton County, Illinois       566   128    22.6\n 5 Gallatin County, Illinois       500    94    18.8\n 6 Menard County, Illinois         780   142    18.2\n 7 Johnson County, Illinois        634   115    18.1\n 8 Brown County, Illinois          724   119    16.4\n 9 Massac County, Illinois         793   129    16.3\n10 Schuyler County, Illinois       836   131    15.7\n```\n\n\n:::\n:::\n\n\n\n**[Hardin County, Illinois has the largest margin or error relative to its estimate. In the census data from 2019-2023, its' population is 3623, and it's margin of error percentage is 45.6%.]**\n\n\n---\n\n## Sorting counties into reliability categories\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data |> \n  mutate(reliability = case_when(\n    moe_pct < 5  ~ \"High confidence\",\n    moe_pct < 10 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n\ncount(county_data, reliability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability         n\n  <chr>           <int>\n1 High confidence    38\n2 Low confidence     21\n3 Moderate           43\n```\n\n\n:::\n:::\n\n\n\n**[High confidence: 38 counties, Moderate confidence: 43 counties, Low confidence: 21 counties]**\n\n---\n\n## Is the margin of error bigger in small places?\n\nTo answer this we need population and our variable side by side, in the same row.\nThat means a **wide** pull.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- get_acs(\n  geography = \"county\",\n  variables = c(myvar = my_variable,\n                pop   = \"B01003_001\"),\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n\nhead(county_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  GEOID NAME                       myvarE myvarM  popE  popM\n  <chr> <chr>                       <dbl>  <dbl> <dbl> <dbl>\n1 17001 Adams County, Illinois        826     43 65166    NA\n2 17003 Alexander County, Illinois    540    214  5042    NA\n3 17005 Bond County, Illinois         735     34 16627    NA\n4 17007 Boone County, Illinois       1011     71 53316    NA\n5 17009 Brown County, Illinois        724    119  6320    NA\n6 17011 Bureau County, Illinois       838     66 33027    NA\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- county_wide |> \n  mutate(moe_pct = myvarM / myvarE * 100) |> \n  mutate(reliability = case_when(\n    moe_pct < 5  ~ \"High confidence\",\n    moe_pct < 15 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n```\n:::\n\n\nNow compare the average population of counties in each reliability category.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide |> \n  group_by(reliability) |> \n  summarize(\n    n_counties = n(),\n    avg_population = mean(popE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  reliability     n_counties avg_population\n  <chr>                <int>          <dbl>\n1 High confidence         38        299458.\n2 Low confidence          10          7787.\n3 Moderate                54         22877.\n```\n\n\n:::\n:::\n\n\n\n**[The average population of a \"high confidence\" county is about 299458, a \"moderate confidence\" county is about 22877, and a \"low confidence\" county is about 7787. This indicates that counties with lower average populations tend to have less reliable, or uncertain, data regarding median gross rent.]**\n\n---\n\n## What this means for policy\n\n1. **Which communities in your state do we know the least about?** \n   The counties in Illinois that we know the least about are Alexander, Brown, Gallatin, Hamilton, Hardin, Johnson, Massac, Menard, Pope, and Schuyler. All 10 of these counties are classified as \"low confidence\" reliability due to their large percentage of margin of error. \n   \n2. **Why?** \n   The American Community Survey (ACS) is based on data that is sampled from the population, rather than surveying every single person like the Decennial Census. Counties with smaller populations will produce a smaller sample size, thus likely resulting in more uncertainty than a large county with a large sample size. When analyzing statistics, a smaller sample size will almost always have a larger margin of error than a larger sample size. This uncertainty is what causes these small counties to have \"low confidence\" reliability. \n   \n3. **What could go wrong?** \n   If a state agency were to allocate resources using this variable, they may over-allocate or under-allocate to any of the 10 \"low confidence\" counties. While over-allocating may waste limited resources and taxpayer dollars, under-allocating can leave many vulnerable people in need. Conversely, it is likely that their allocations for larger counties, which typically fall in the \"high confidence\" reliability due to their small margins of error, will be accurate. Treating every county's number as equally certain is inherently unfair to small counties. \n\n\n**[Upon learning how the ACS operates, I was naively shocked to find out that the data is extrapolated from a much smaller sample size, not the entire population. In my childhood, I imagined government workers going door to door with detailed paper surveys that they would then spend months logging into a large complex computer software. After Friday's class, I found myself questioning the ethics of creating policy, even if it is positive, based off of data that may not be entirely comprehensive or representative of the people which whom it will affect. After completing this assignment, I am even further convinced that there must be another way to understand people, where they live, and how they live. I think that this is where I see community engagement operating most effectively. Bridging the gap between what is \"data\" and what is \"reality\". Although data analytics can be excellent at analyzing large overarching trends, I think in some ways it fails to get as fine tuned as one would hope, at least regarding census data. As spatial analysts, we have a responsibility to understand and communicate not just the great potential of data analysis, but also it's limits.]**\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}